# Generated by Django 3.2.5 on 2021-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reading', models.IntegerField(verbose_name='parameter')),
                ('latitude', models.IntegerField(verbose_name='lat')),
                ('longitude', models.IntegerField(verbose_name='long')),
            ],
        ),
    ]
