# Generated by Django 3.2.5 on 2021-08-12 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
